<a href="https://colab.research.google.com/github/ToluSh/ISE326-Ass/blob/main/NumpyExercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Text cell <undefined>
# %% [markdown]
# HW1 - NumPy Exercise

## Exercises

Answer the questions or complete the tasks outlined in bold below, use the specific method described if applicable.

Maximum Number of Points: 40.
Questions 1-20 (2 points each).

Text cell <undefined>
# %% [markdown]
#### 1. Import NumPy as np
import numpy as np

Code cell <undefined>
# %% [code]

Text cell <undefined>
# %% [markdown]
#### 2. Create an array of 10 zeros

Code cell <undefined>
# %% [code]
np.zeros(10)
Execution output
0KB
	text/plain
		array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Text cell <undefined>
# %% [markdown]
#### 3. Create an array of 10 ones

Code cell <undefined>
# %% [code]
np.ones(10)
Execution output
0KB
	text/plain
		array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Text cell <undefined>
# %% [markdown]
#### 4. Create an array of 10 fives
5 * np.ones(10)
Code cell <undefined>
# %% [code]

Execution output
0KB
	text/plain
		array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Text cell <undefined>
# %% [markdown]
#### 5. Create an array of the integers from 10 to 50

Code cell <undefined>
# %% [code]
np.arange(10,51)
Execution output
0KB
	text/plain
		array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
		       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
		       44, 45, 46, 47, 48, 49, 50])

Text cell <undefined>
# %% [markdown]
#### 6. Create an array of all the even integers from 10 to 50

Code cell <undefined>
# %% [code]
np.arange(10,51,2)
Execution output
0KB
	text/plain
		array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
		       44, 46, 48, 50])

Text cell <undefined>
# %% [markdown]
#### 7. Create a 3x3 matrix with values ranging from 0 to 8

Code cell <undefined>
# %% [code]

np.arange(0,9).reshape([3,3])

Execution output
0KB
	text/plain
		array([[0, 1, 2],
		       [3, 4, 5],
		       [6, 7, 8]])

Text cell <undefined>
# %% [markdown]
#### 8. Create a 3x3 identity matrix

Code cell <undefined>
# %% [code]
np.eye(3)

Execution output
0KB
	text/plain
		array([[1., 0., 0.],
		       [0., 1., 0.],
		       [0., 0., 1.]])

Text cell <undefined>
# %% [markdown]
#### 9. Use NumPy to generate a random number between 0 and 1

Code cell <undefined>
# %% [code]
np.random.rand(1)
Execution output
0KB
	text/plain
		array([0.72061738])

Text cell <undefined>
# %% [markdown]
#### 10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

Code cell <undefined>
# %% [code]
np.random.randn(25)

Execution output
0KB
	text/plain
		array([-0.29233072,  0.6149879 ,  0.62826371, -0.41211443,  0.07533853,
		       -1.05007604,  0.48632808,  0.32808645,  0.29371673, -0.07529016,
		        0.38813823,  0.61931288, -0.24723198, -0.60339607,  0.21665797,
		       -0.67345814,  0.445508  , -1.97456597,  1.96788751,  1.18614563,
		        1.45326745, -0.59075696, -1.58267156, -2.78914624,  0.69546833])

Text cell <undefined>
# %% [markdown]
#### 11. Create the following matrix:

Code cell <undefined>
# %% [code]
np.linspace(0.01,1, 100).reshape([10,10])

Execution output
1KB
	text/plain
		array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
		       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
		       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
		       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
		       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
		       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
		       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
		       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
		       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
		       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

Text cell <undefined>
# %% [markdown]
#### 12. Create an array of 20 linearly spaced points between 0 and 1:

Code cell <undefined>
# %% [code]
np.linspace(0,1,20)
Execution output
0KB
	text/plain
		array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
		       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
		       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
		       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Text cell <undefined>
# %% [markdown]
## Numpy Indexing and Selection

Now you will be asked to replicate the resulting matrix outputs:

Code cell <undefined>
# %% [code]
# 13. Denote the matrix below as mat (you can create such a matrix using arange() and reshape()).

Code cell <undefined>
# %% [code]

Execution output
0KB
	text/plain
		array([[ 1,  2,  3,  4,  5],
		       [ 6,  7,  8,  9, 10],
		       [11, 12, 13, 14, 15],
		       [16, 17, 18, 19, 20],
		       [21, 22, 23, 24, 25]])

Code cell <undefined>
# %% [code]
# 14. WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

Code cell <undefined>
# %% [code]

Execution output
0KB
	text/plain
		array([[12, 13, 14, 15],
		       [17, 18, 19, 20],
		       [22, 23, 24, 25]])

Code cell <undefined>
# %% [code]
# 15. WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

Code cell <undefined>
# %% [code]

Execution output
0KB
	text/plain
		20

Code cell <undefined>
# %% [code]
# 16. WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

Code cell <undefined>
# %% [code]

Execution output
0KB
	text/plain
		array([[ 2],
		       [ 7],
		       [12]])

Code cell <undefined>
# %% [code]
# 17. WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

Code cell <undefined>
# %% [code]

Execution output
0KB
	text/plain
		array([21, 22, 23, 24, 25])

Text cell <undefined>
# %% [markdown]
### Now do the following

Text cell <undefined>
# %% [markdown]
#### 18. Get the sum of all the values in mat, which is the matrix that question 13 asked you to create

Code cell <undefined>
# %% [code]

Execution output
0KB
	text/plain
		325

Text cell <undefined>
# %% [markdown]
#### 19. Get the standard deviation of the values in mat

Code cell <undefined>
# %% [code]

Execution output
0KB
	text/plain
		7.211102550927978

Text cell <undefined>
# %% [markdown]
#### 20. Get the sum of all the columns in mat

Code cell <undefined>
# %% [code]

Execution output
0KB
	text/plain
		array([55, 60, 65, 70, 75])




SyntaxError: ignored